# Generated by Django 4.2 on 2024-12-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tropicanaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('organization_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=150)),
                ('has_job_description', models.BooleanField()),
                ('job_description_file', models.FileField(blank=True, null=True, upload_to='job_descriptions/')),
                ('preferred_service', models.CharField(choices=[('Job Advertising Only', 'Job Advertising Only'), ('Job Advertising & Shortlisting Service', 'Job Advertising & Shortlisting Service')], max_length=50)),
                ('payment_option', models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
