# Generated by Django 4.2 on 2024-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tropicanaapp', '0002_jobadvert'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('organization_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('help_message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
