# Generated by Django 4.2 on 2024-12-01 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tropicanaapp', '0003_recruitmentinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentinquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed')], default='Pending', max_length=50),
        ),
    ]
