# Generated by Django 4.2 on 2024-12-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tropicanaapp', '0004_jobadvert_user_recruitmentinquiry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('organization_name', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_no_or_passport', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('cv', models.FileField(upload_to='cv_uploads/')),
                ('id_copy', models.FileField(upload_to='id_copy_uploads/')),
                ('reason_for_consideration', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tropicanaapp.job')),
            ],
        ),
    ]
