# Generated by Django 4.2 on 2024-12-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tropicanaapp', '0005_job_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvert',
            name='has_job_description',
            field=models.BooleanField(default=False),
        ),
    ]
